### ISSUE TITLE
Cocoapod: Unable to find a specification for `NetatmoSwiftAPI (~> 0.0.1)`

### ISSUE THREAD

**Issue by iKK001** [Baza207/NetatmoSwiftSDK#1]
Hi James,
  first of - many thanks for your work ! I intend to use your Netatmo iOS SDK for an App.

I try to use Cocoapods dependency manager, using:

```
pod 'NetatmoSwiftAPI', '~> 0.0.1'
```

Unfortunately, I tried the `pod install` with Cocoapods - but I always get the following error message:

```
[!] Unable to find a specification for `NetatmoSwiftAPI (~> 0.0.1)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Of course, I have done the `pod repo  update` before. 

Do you have any idea why Cocoapods does not work ?

Thanks for any support on this !

**Comment by Baza207** [comment]
Hey, I think I actually need to up the version number to a minimum of `0.1.0` for it to work properly with CocoaPods. Though sadly I haven't found time lately to look into it further.

I do know that SwiftPM should work if that's any help, as that's how I'm using it in my app. 🙂

I haven't done much work on this lately due to other commitments but hopefully will jump back into it soon to fix some issues I know are there. 👍

**Comment by iKK001** [comment]
Thank you James, for the ultra quick response !
I will try `0.1.0` (or SwiftPM maybe as well...)...

I know how it goes with commitments :) Don't worry, I am more than happy to have found this nice work-basis.

**Comment by iKK001** [comment]
Hm, I tried SwiftPM with...

`.package(url: "https://github.com/Baza207/NetatmoSwiftAPI.git", .upToNextMajor(from: "0.0.1"))` inside the dependencies.

But when I try to create the .xcproj with `swift package generate-xcodeproj` is bring the following error message:

```
Fetching https://github.com/Baza207/NetatmoSwiftAPI.git
error: Failed to clone https://github.com/Baza207/NetatmoSwiftAPI.git:
    Cloning into bare repository '/Users/user/Documents/docs/programming/iPhone_applications/Learning/Watch/myapp/.build/repositories/NetatmoSwiftAPI-686023e4'...
    remote: Repository not found.
    fatal: repository 'https://github.com/Baza207/NetatmoSwiftAPI.git/' not found
```

**Comment by Baza207** [comment]
Ok, I'll have to have a look into that as well.

I know it does work however if you add it with SwiftPM inside a project in Xcode.

So if you go into the Project in Xcode and select the "Swift Packages" tab, you should be able to add it using that (which is how I've previously done it).

Let me know if you have any further issues though, and I'll look into them when I can.

**Comment by iKK001** [comment]
Still with the Package Manager, I know what the issue must be:

When under File-->Swift Package-->Add dependency..., I can add other packages (such as Realm). However, when I enter your URL (https://github.com/Baza207/NetatmoSwiftAPI.git) then I get the following user-credential mask:

![Screenshot 2020-05-07 at 14 54 27](https://user-images.githubusercontent.com/8404556/81296949-efad3980-9072-11ea-8f48-4b06f355b0b2.png)

I suspect that your repo is PW protected of some sort. 

And this might be the problem for Cocoapods as well (...not sure...).

Could you please make it a free git repo so that the Package Manager can use it ?

**Comment by Baza207** [comment]
Umm that's very strange. The repo should be open and doesn't have any password protection on it.

I'll have a look into this when I can (not sure when I'll be able to though) and get back to you with any fixes/solutions. 🙂

**Comment by MarcoMirisola** [comment]
Hello, I had the same problem.
The documentation is wrong it should be NetatmoSwiftSDK and not NetatmoSwiftAPI

**Comment by iKK001** [comment]
Thank you James !

**Comment by iKK001** [comment]
@Marco:  I tried NetatmoSwiftSDK (with Cocoapods) but it did not work either... What was your `pod` line ?
Or did you use it inside Swift Package Manager. And if yes, what is the correct url ?

**Comment by Baza207** [comment]
I think, @MarcoMirisola has it (for SwiftPM). I was naming it 2 things at the start and obviously forgot a rename in the README.

This wont fix the issue for CocoaPods, as I think that's still an issue with CocoaPods not liking versions less than `0.1.0`. So for that I'll have to submit a new version to them and bump the project to min of `0.1.0`.

**Comment by iKK001** [comment]
I can live with SwiftPM - but what is the correct url there ?
Is it: `https://github.com/Baza207/NetatmoSwiftSDK.git`

Ah yes, it works !!!! The above url did it inside Swift Package Manager.

**Comment by MarcoMirisola** [comment]
I managed to use it with cocoapods using pod 'NetatmoSwiftSDK', '~> 0.0.1'
Try pod repo update before pod install

**Comment by Baza207** [comment]
I've just updated the README, as well as double checked it with all package managers. It should now working using `NetatmoSwiftSDK` (not `API`). Thanks for catching this, that'll teach me to not check the project properly after renaming it last minute. 😄
