### ISSUE TITLE
how to set up URL scheme

### ISSUE THREAD

**Issue by iKK001** [Baza207/NetatmoSwiftSDK#3]
Hi James,

  I am struggling with setting up the URL-scheme. Could you please give me a hint on how to do so correctly inside Xcode ?

I have the following URL scheme defined:
![Screenshot 2020-05-11 at 13 52 57](https://user-images.githubusercontent.com/8404556/81558975-ea136480-938e-11ea-8e38-2d35ce6d16ee.png)

On Netatmo, I have my user clientID and clientSecret and I use it in my iOS Swift code as your manual states:
```
NetatmoManager.configure(clientId: "<Client ID>", clientSecret: "<Client Secret>", redirectURI: "<Redirect URI>://auth")
```

On the Netatmo site, I need to place the Redirect-URI.
(I placed:  `https://com.mydomain.myappname`) - and IT ABSOLUTELY REQUIRES AN URL.

Inside Xcode, however, it sais  that URL-schemes cannot contain words such as ` http, https, mailto, tel, sms, etc`.

Here my questions:

1. From the definition of my URL scheme, how does this Netatmo Rederict-URI correspond?
(i.e. are my above settings all correct ?)

2. Inside your manual, you often write `<Rederict URI>` as a placeholder - does this involve `https://com.mydomain.myappname` or just `com.mydomain.myappname` or just `myappname`.

3. How does the Xcode URL-scheme look like exactly in order for this to work ??
(i.e. with or without `https://` ??

It is very confusing to me how each entry must be ???

Do you have a working example or could you maybe precise your manual ?

Right now, my biggest problem is that after the Auth-Screen from Netatmo, my App wants to redirect to Safari with the Redirect-URI) - BUT IT DOES NOT END UP IN THE APPDELEGATE "open url" method. (because `https://`url-schemes are not caught in side AppDelegate).

What do I need to do ?

Thank you so much.

And last question:

Is it correct that using your SDK, the user will always need to authorise Netatmo first (and then the App can handle the callback) ?  Is it possible to anonymously authorise the iOS App (i.e. without auth-screen ? 

I tried to use "login" directly instead of NetatmoManager.authorizeURL, like in your Weather Tests:
`NetatmoManager.login(username: config.username, password: config.password, scope: []) { (result) in ... }`

But it caused an error: `'login' is inaccessible due to 'internal' protection level`

So maybe you can tell me what the best approach is for this ?

Thank you for your support !

**Comment by iKK001** [comment]
I also tried "Universal Links" (with a so-called apple-app-site-association file).

But same thing, after the Authorization acceptance button-press, Safari opens instead of the iOS-App callback !

How does this work ?

**Comment by Baza207** [comment]
Hey, so I'll try to answer your questions as best I can, though I'd suggest having a look at some general resources online, as this is just as much a OS feature issue rather than something for this framework.

I link this in the README, but I might have hidden it a bit: https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

I might try and make a blog post for a step by step, but I'll see how much time I get tonight, assuming the below doesn't help (though I might anyway incase I forget all this in the future too).

So to answer your questions:

1. You don't have to define any URI scheme with Netatmo and their dev portal. That is only for if you're using their API in a web app. Because we're in an iOS app, we're using the OS level features, in this case custom URL schemes.

2. So, a URL scheme is a part of a URL. The scheme for "the web" is `https` (or `http`). When you define your own custom scheme that's what you're creating, the text before the `:` This is how opening the mail app with `mailto:` or phone with `tel:`generally  work. You can see a (very old) list of native Apple ones [here](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html). Examples of custom ones from other apps are Facebook who use `fb://` and Twitter who use `twitter://`. A good list can be found [here](https://ios.gadgethacks.com/news/always-updated-list-ios-app-url-scheme-names-0184033/) as examples. So remember to try and make it unique but not too crazy long (I'm not sure if you can/should use `.` but I've always used `-` instead. Not sure if that actually means something or just what I do).

3. I think I sort of answered this when answering your second question, but you're **not** going to have a URL with `https://` you'll have a URL with your own scheme, so something like `myappname://<rest of the URL>`. This is why if you're using `https://` iOS see's that scheme as a web URL and opens it in Safari. The scheme tells iOS what to do with it (else fallback to safari I think).

    As an extra point here, when I use `auth` in the README for the rest of the URL after `://`, this could be anything. You could use `woopwoopputyourhandsintheair`, It doesn't matter. I just use `auth` as it makes sense and is readable. A URL callback could be done for multiple things (in this case only one though) so it's just nice to have another thing to tell you what is the reason for the callback.

To answer your additional question:

This SDK is simply a wrapper around the Netatmo API. This means that if the API needs authentication (which I think as of this moment all the calls do) then this SDK will need them as well.

The function to login with username and password is marked as internal for a couple of reasons, 1) it's marked in the Netatmo docs just to be used in testing and not in live production. So as the SDK gives a way of using the OAuth2 login function it's just used internally for the tests of the SDK. 2) Because I've added extra logic around the OAuth2 API as part of this SDK that automatically tracks, stores and refreshes tokens when it needs to (saving items in the keychain etc), I can only use the login for tests, as you don't get access to the keychain as a framework. (I lost a fair few hours working that ones out.)

Last of all, universal links is a whole different ball game, but not needed by this SDK and so beyond the scope. Leave that one for another day. 😉

I hope this helps, and if you need any more help with this, I'll try and look into creating some more resources to help.

I'll close this issue now as I think it's off-topic, due to the nature of being more a OS feature question. 🙂

**Comment by iKK001** [comment]
Thank you very much. Hmm, it still does not work.

Here is what I do:

Inside AppDelegate.swift I write the following (id's are fake..) :

```
NetatmoManager.configure(clientId: "3dc3d9a2xr1aqyu256215m4ab", clientSecret: "MeSxr32aeadddsomeID1tdmNadldMs", redirectURI: "myscheme://com-myorg-myappname://auth")
```

Inside Info tab of Xcode I define a corresponding URL-type as follows:

![Screenshot 2020-05-11 at 23 13 36](https://user-images.githubusercontent.com/8404556/81612411-10f88780-93dd-11ea-9518-56b433f751c1.png)

Inside AppDelegate.swift I add the following method :

```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        
    if url.scheme == "myscheme" && url.host == "auth" {
        NetatmoManager.authorizationCallback(with: url)
        return true
    }
        
    NSLog("No matching URL contexts")
    return false
}
```

Inside any ViewController I write :

```
var listener: NetatmoManager.Listener?
    
override func viewDidLoad() {
    super.viewDidLoad()
        
    listener = NetatmoManager.addAuthStateDidChangeListener { (authState) in  
      // Handle state change
        print(authState)
    }
        
    let url: URL
    do {
        url = try NetatmoManager.authorizeURL(scope: [.readStation])
    } catch {
        // Handle error
        return
    }
    UIApplication.shared.open(url, options: [:], completionHandler: nil)
}
```

The problem now:

The `NetatmoManager.authorizeURL(...)`-method only redirects to the Netatmo-Auth page inside the App in the case I place a valid https:// URL in the Netatmo App Technical Parameters.

And if I place a non-https-based URL inside `NetatmoManager.configure(...)`-method, then no Netatmo-Authorization page is opened at App startup and also, NO AppDelegate Callback is happening.

Since the "redirectURL" inside the `NetatmoManager.configure(...)` method does not contain a https-URL - there can't be a link to the Netatmo App-Technical-Parameters and therefore no "Netatmo-Authorization page" is opened at iOS-App startup. If I place a https-based URL inside 'NetatmoManager.configure(...)'-method and inside Netatmo App Technical Parameters credentials, than at least the Authorization page opened inside the iOS App.

With a non-https-based URL (such as in my example 'myscheme://com-myorg-myappname://auth', no Authorization page opens and also no AppDelegate-callback kicks in. In fact, nothing happens !!!

So what do I do wrong in the above code samples ?? And how exactly do you create the URL-type inside Xcode ? Is my screenshot ok like this together with the code-example above ? But why is there no AppDelegate-callback kicking in ? and why is there no Netatmo Authorization-page opening as long as I use a non-https-based URL ??

And did I understand correctly, I do not have to put any Netatmo App Technical Parameter in the  "redirect URI" credential field (where I created the Netatmo-project and where I get the clientID and clientSecret from) ???

**Comment by Baza207** [comment]
Just reading the first part of the above, you seem to be using 2 schemes in your URI. You don't need the `identifier` when defining your custom URL scheme (in this case) and writing `myscheme://com-myorg-myappname://auth` is like writing `https://http://apple.com`. It's an invalid URL.

Even just fixing the URL passed to `NetatmoManager.configure(_:)` as `myscheme` should fix your issue.

It's confusing I know, but you're not passing a URL into `configure()` you're passing a URI. Which is a identifier rather than a location (maybe think post code rather than full address).

**Comment by Baza207** [comment]
Looking through the rest of what you've written, I think your code is correct. You're just getting confused between URI, URL Schemes and URLs. 🙂

Maybe the following might help you understand some more. This is the authentication process:

1. You define your URL scheme with Xcode, `myscheme` in your examples (the identifier field is ignored in this case)
2. You pass your scheme the `configure(_:)` as the URI (which is an identifier)
3. You call `authorizeURL(_:)` and the SDK uses your keys and URI to generate a web URL (`https://api.netatmo.com/oauth2 etc`) which as part of the URL parameters includes the `redirect_uri` along with any other information (`client_id`, `scope` and unique `state` UUID)
4. You pass this URL to Safari (however you want, `openURL(_:)` etc)
5. Netatmo authenticates your request by the asking the user to log in and accepting the scope you're requesting
6. Once successfully authenticated, Netatmo creates a URL with your URI that was passed in the request (along with some other things like that `state` UUID to know that the request that took the user out of the app is the same one that brought them back in) with a `code` which the SDK stores and uses to generate OAuth2 tokens

And (hopefully) bingo, you're back in the app with an authenticated user. I hope this helps clarify. 😄

**Comment by iKK001** [comment]
Ah, I understand.

I advanced a little bit:

Right now I have:

Inside AppDelegate's didFinishLaunchingWithOptions method:
```
NetatmoManager.configure(clientId: "3dc3d9a2xr1aqyu256215m4ab", clientSecret: "MeSxr32aeadddsomeID1tdmNadldMs", redirectURI: "myschemename://auth")
```

Inside Xcode URL types:

![Screenshot 2020-05-11 at 23 41 41](https://user-images.githubusercontent.com/8404556/81615018-34bdcc80-93e1-11ea-9ee1-bacad2efa263.png)

And inside AppDelegate:

```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        
    if url.scheme == "myschemename" && url.host == "auth" {
        NetatmoManager.authorizationCallback(with: url)
        return true
    }
        
    NSLog("No matching URL contexts")
    return false
}
```

Now the App asks at startup:

![screnshot01](https://user-images.githubusercontent.com/8404556/81615403-d1806a00-93e1-11ea-90ce-4a69a2609f15.png)

And the listener delivers the following error message:

```
listener = NetatmoManager.addAuthStateDidChangeListener { (authState) in
    print(authState)
}
```

Error message: ` failed(NetatmoSwiftSDK.NetatmoError.noCallbackCode) `


Questions

1. How can I get rid of the confirmation screen  (see screenshot above)

2. What is still wrong (i.e. what does the above error-message mean ??

Thanks!

**Comment by Baza207** [comment]
1. You can't. That's just iOS security at work.
2. ~~Remote the `://auth` part in `configure(_:)` It should just be `...redirectURI: "myschemename")`~~

~~You're passing in a URI (Uniform Resource **Identifier**), an identifier, not a URL (Uniform Resource **Locator**).~~

Strike that last, I'm getting myself confused now 😛

**Comment by iKK001** [comment]
laugh - yes, I was going to say, this did not help.

The redirectURI:   "myschemename://auth" did work better !

But something else must be wrong.

And question: Can you at least customise the iOS-security screen (i.e. customise my screenshot from above ??)

**Comment by Baza207** [comment]
Ok, are you using scenes in your iOS project? If you created a new project with Xcode 13, you probably are. Go back and check the README, as you need to be putting the callback in the `SceneDelegate`, not the `AppDelegate`.

No you can't customise this security dialogue.

**Comment by iKK001** [comment]
yes, I do use Scenes (iOS13) - but I also need to support iOS12. Is it better to only work with AppDelegate (and no SceneDelegate ) in that case ??

**Comment by Baza207** [comment]
If you need to support both, then you have to have both routes. It's a bit too much for me to explain how to do that more than you need code in both places. As iOS 13 will look in the `SceneDelegate`, but iOS 12 will look in the `AppDelegate` (as it doesn't know that scenes exist). iOS 13 will not fall back to looking in the `AppDelegate` unless you completely strip out scenes from your project (which you probably don't want to do as you'll want something in there at some point for iOS 13 features). Here lies the fun of backwards compatibility. 😛

**Comment by iKK001** [comment]
ok, makes sense:

My scene delegate method looks like this (and that's exactly where it kicks in now under iOS13):

```
    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {

        guard let url = URLContexts.first?.url else {
            NSLog("No valid URL contexts")
            return
        }

        if url.scheme == "myschemename" && url.host == "auth" {
            NetatmoManager.authorizationCallback(with: url)
        } else {
            NSLog("No matching URL contexts")
        }
    }
```

The callback is working - the `NetatmoManager.authorizationCallback(with: url)` is called - but right after this, the listener-callback inside my ViewController prints out the error message:

```
listener = NetatmoManager.addAuthStateDidChangeListener { (authState) in
            // Handle state change
            print(authState)
        }
```

prints out :  `failed(NetatmoSwiftSDK.NetatmoError.noCallbackCode)`

What is wrong in that case ?

**Comment by Baza207** [comment]
I'm afraid I'm now at a loss on what to say. I'm guessing the username and password you're entering in the Netatmo web page are correct?

The error means when parsing the URL returned it found no `code` parameter. The `code` is what is used to generate the OAuth2 token(s) and so it couldn't go any further.

Are you just sending a single scope or multiple? If multiple there's an issue in v0.0.1 that I've fixed in the `develop` branch but not pushed in a new version (part of the way through other things as well). I detail this a bit in issue #2 

Either way, it might be good to try using the develop branch for now, until I'm able to push v0.0.2 or similar.

**Comment by iKK001** [comment]
So far, I never see a Netatmo username and password field ? The only screen I get inside my iOS App is the screenshot I show above (i..e black screen that asks to open inside the App).

Am I supposed to see a login screen of some sort ??

I place all my code in the entries above - am I missing something ??

**Comment by Baza207** [comment]
Oh, yes you are. THat's the point of being kicked out to a web page. 😄

So something must still be wrong somewhere with your confutation. Are you able to print the URL that is returned when your app is re-opened? If so can you paste it here (removing any keys etc)?

It should be something like this:
```
myschemename://auth?state=<some UUID>&code=<alphanumeric code>
```

**Comment by iKK001** [comment]
Ah I've found out what was wrong:  I still had a URI in the Netatmo App Technical Parameters (i.e. credential page of my Netatmo project). Once I deleted it from there, I now get a Third-party-App confirmation screen (every time I open the app) and the extra "open in..." confirmation once I press the "Yes, I accept" button !!!

I guess I'm almost there !

Question: Is it correct that this "Yes, I accept" confirmation ALWAYS shows up at EVERY App startup ? If no, how would I only bring it up once ??

**Comment by Baza207** [comment]
Might be useful as well if you can share the URL created by `authorizeURL(_:)` (stripping any keys again). Just incase something shows up there that could answer this.

I need to go to bed, but really want to solve this now. 😅

**Comment by iKK001** [comment]
Here is the URL created by `authorizeURL(_:)`:

```
https://api.netatmo.com/oauth2/authorize?client_id=ab3awaf32a0mdnadasdfsaeea&redirect_uri=myschemename://auth&scope=read_station&state=65BG344B-35BC-34SA-BS35-9234aBADFE350
  - _url : https://api.netatmo.com/oauth2/authorize?client_id=a33abdMadde355323&redirect_uri=myschemename://auth&scope=read_station&state=343DAdaB35-35AA-32DS-M033-1345BADD993334
```
(all keys fake)

**Comment by iKK001** [comment]
You helped me already a lot !  Maybe we continue tomorrow ! It is late for me too !!
I thank you for your effort. I think we are close. I will make some more trials myself and get back to you with summarised questions, ok?

**Comment by Baza207** [comment]
Ah great, that's progress. 😄 

No, but you don't have to authenticate the user every time you open the app. I'd suggest listening to auth status (like I saw you were doing before) but only request the user authenticate if the status is `.unauthorized`.

Genrally:

`.unknown` = Not loaded or configured yet, waiting for state.
`.authorized` = All ready to go
`.tokenExpired` = We have a authorised user with a `code` but generating a OAuth2 token from that code failed. (see below here)
`.unauthorized` = Not logged in, use `authorizeURL(_:)` here
`failed(_ error: Error)` = The world is burning, politely let the user know not to panic

You *shouldn't* get token expired, but if you do you don't have to manually call to refresh the token (which isn't public in v0.0.1 anyway so you wont be able to call it) and you also *shouldn't* manually get the user to re-auth with `authorizeURL(_:)`. Tokens should be regenerated on any fetch request or on authentication if they've expired. So if calling to get a new token fails (no internet for example) the SDK should request a new token the next time you request something again.

**Comment by iKK001** [comment]
aha makes sense !  However, .unauthorized is not part of the callback (yet?). And therefore I call `authorizeURL(_:)` maybe if .unknown occurs (at least that's what it is after first app install and launch. Is this ok?

Available states in my listener-callback are:

`authorized`
`unknown`
`failed(_ error: Error)`
`tokenExpired`

**Comment by Baza207** [comment]
`.unautherized` is a state returned inside of `addAuthStateDidChangeListener(_:)`. That should return `.unknown` then `.unautherized` once the SDK is configured. Though I’m not at my Mac now to double check. However you should only call to authorise the user when you get `.unautherized` as you’re likely to always get `.unknown` while things are setting up or trying to get previous state from they keychain, etc.

**Comment by iKK001** [comment]
I am happy, I just got the following code to spit out my first data:

```
    var listener: NetatmoManager.Listener?

    override func viewDidLoad() {
        super.viewDidLoad()
        
        listener = NetatmoManager.addAuthStateDidChangeListener { (authState) in
            print(authState)
            if authState == .unknown {
                let url: URL
                do {
                    url = try NetatmoManager.authorizeURL(scope: [.readStation])
                } catch {
                    // Handle error
                    return
                }
                UIApplication.shared.open(url, options: [:], completionHandler: nil)
            } else {
                
                NetatmoWeather.getWeatherStationData { (result) in
                    
                    switch result {
                    case .success(let stationData):
                        print(stationData)
                    case .failure(let error):
                        print(error)
                    }
                    
                    // try? NetatmoManager.logout()
                }
            }
        }
    }
```

At first startup of the App after installing it fresh, it does the Netatmo-"Yes, I accept" question. 

At second startup of the App, I got this log:

```
authorized

Station(user: User(mail: mymail@myaddr.com, administrative: Administrative(localeCode: de, unit: metric, windUnit: kph, pressureUnit: mbar, feelsLikeAlgorithm: humidex)), devices: [])
```

**Comment by iKK001** [comment]
About the ".unknwon" vs. ".unauthorized":

The `listener = NetatmoManager.addAuthStateDidChangeListener { (authState) in ...}` callback does not allow anything except the 4 cases for `authState`. i.e. there is no `.unauthorized` since the compiler does not allow this. But this might just be a version 0.0.1 vs. 0.0.2 thing, or not?

**Comment by iKK001** [comment]
Anyway, I think we can leave it here. You helped me a tremendous amount ! And I thank you for this. I will play some more with your API and get back to you once I have more concrete questions. My goal ist to get world-weather - but for this, I need to study your API better first.

**Comment by Baza207** [comment]
Great! 🎉 Glad you got it working. I’d suggest using a `switch` to differ between auth states instead of an `if else` statement. But I’m glad it’s working for you. Good luck with your project. 🙂

**Comment by iKK001** [comment]
Thank you very much !!  Yes, I'll definitively use a switch statement. This was just quick and dirty to get something spat-out :)

**Comment by iKK001** [comment]
Hi James,
  I have some more general questions relating the Netatmo iOS SDK:

1. Is it possible to get public Weather-data without User-Authentication ?
(i.e something like `NetatmoWeather.getPublicData(northEast: ..., southWest: ...)` but without prior Authentication ?)

2. Is it possible to make the Authentication-Page autofill with the username/pw of my Netatmo App-account ? If yes, how ?

3. Is it possible to make a login to my Netatmo App-account from within my Swift code directly ? (i.e. something like `NetatmoManager.login(username: ..., password: ...)`. 
(The login should be instead of authentication-page !)

4. In your gitrepo example I see the code `NetatmoManager.login(username: config.username, password: config.password, scope: scope) { (result) in ...}` - Is this login-method part of another version or why does this login-method not exist in my NetatmoManager ?

Thank you for clarifying !

**Comment by Baza207** [comment]
Just to finalise this with your last point about `.unautherized`. It does get called, and actually `.unknown` is the one that is unlikely to get called. I have this in my `viewDidLoad(_:)` method in my root view controller:

```swift
authStateListener = NetatmoManager.addAuthStateDidChangeListener { [weak self] (authState) in
    
    guard let self = self else {
        return
    }
    
    switch authState {
    case .authorized:
        // TODO: Start fetching data
        break
        
    case .unauthorized:
        // TODO: Show login view controller
        break
        
    case .failed(let error):
        print("Auth failed: \(error.localizedDescription)")
        // TODO: Present error to the user
        
    case .unknown, .tokenExpired:
        // This should never be called or needed to be reacted to
        break
    }
}
```

`AuthState` is a public enum defined in `NetatmoManager` and all cases should be public.

**Comment by Baza207** [comment]
@iKK001 Do you mind opening a new issue for your general questions, just as we can keep this already long issue about this topic?

**Comment by iKK001** [comment]
yes, let me do that !

**Comment by iKK001** [comment]
About the ".unauthorized" :

I get the following error inside my code (see screenshot)

![Screenshot 2020-05-12 at 12 26 13](https://user-images.githubusercontent.com/8404556/81673400-e0036b80-944b-11ea-9110-09e332eeb95c.png)

This is my pod-version

```
pod 'NetatmoSwiftSDK', '~> 0.0.1'
```

**Comment by Baza207** [comment]
Ah, I did add it since 0.0.1, my bad. I'm looking to push a few changes soon (though not sure how soon, soon is. 😛), and that will include that along with a few minor fixes and changes (some might break your code, but that's the joys of using a in development framework 😉 Nothing too crazy though).

**Comment by iKK001** [comment]
ok - no problem ! I am looking forward to the new push (whenever it comes out 😛) :)

In the meantime, I use ".unknown" to cause the Auth-process...

**Comment by Baza207** [comment]
@iKK001 I created some documentation about this now. If you have a moment to look though and let me know if it looks good from our discussions and your experience, it’d be much appreciated. 😄 

https://github.com/Baza207/NetatmoSwiftSDK/blob/master/Documentation/Authentication-Setup.md

**Comment by iKK001** [comment]
Dear James,

  sorry for my delay - I was too busy with starting a new job as an iOS programmer at a startup.

Thank you for Cocoapod v0.0.2

And thank you very much for the documentation - this is great.

Below are my two, three suggestions at first read :  (feel free to use them as it serves you)

Sincerely
  Stephan

Suggestions to documentation :

1. I did not find a link to the documentation in the readme - my suggestion: make it a dominant title in the readme with a link to the Authentication-Setup.md and/or Testing.md

2. As far as I remember our nightly discussion - it was not obvious to me that certain methods only apply in UnitTests. This could be explained somewhat better in your doc (or at least it should be mentioned, I think)

3. one important thing I remember:  Creating an App at Netatmo webpage, you should not fill out the “redirect URI” field ! It must be clear that the Xcode URL-scheme is in no way related to the Netatmo redirectURI (at least for me, this was very unclear at first). If redirectURI is not empty, the iOS App does not navigate properly to the Authentication ViewController. (also webhook URI I left blank)
I remember, with a wrong behaviour later in the App - I still had a URI in the Netatmo App Technical Parameters (i.e. credential page of my Netatmo project). Once I deleted it from there, my iOS App would then navigate properly to the Third-party-App confirmation screen (Auth-ViewControler), not before.
Maybe you could state this more clearly in your documentation.

The correct way is to leave the URI-fields blank !

**Comment by Baza207** [comment]
Thanks for the suggestions. I'll try and implement them when I get a moment. 👍

Hope the new job is going well. 😄
