### ISSUE TITLE
Login to Netatmo account

### ISSUE THREAD

**Issue by iKK001** [Baza207/NetatmoSwiftSDK#4]
Hi James,
I have some more general questions relating the Netatmo iOS SDK:

1. Is it possible to get public Weather-data without User-Authentication ?
(i.e something like NetatmoWeather.getPublicData(northEast: ..., southWest: ...) but without prior Authentication ?)

2. Is it possible to make the Authentication-Page autofill with the username/pw of my Netatmo App-account ? If yes, how ?

3. Is it possible to make a login to my Netatmo App-account from within my Swift code directly ? (i.e. something like NetatmoManager.login(username: ..., password: ...).
(The login should be instead of authentication-page !)

4. In your gitrepo example I see the code NetatmoManager.login(username: config.username, password: config.password, scope: scope) { (result) in ...} - Is this login-method part of another version or why does this login-method create the following error message ?

![Screenshot 2020-05-12 at 12 29 46](https://user-images.githubusercontent.com/8404556/81673732-60c26780-944c-11ea-8e69-ff662b012196.png)

Thank you for clarifying !

**Comment by Baza207** [comment]
1. As I think I said before, this SDK is just a wrapper around the Netatmo API. Therefore if they require authentication (which I think they do for all calls, most likely for limiting as well as security purposes) then this SDK does as well.

    Double checking the [Netatmo docs](https://dev.netatmo.com/apidocumentation/weather#getpublicdata) it does seem that `getpublicdata` for Weather doesn't require a scope. However, not requiring a scope still requires authorisation, as to make any request the API still requires an OAuth2 token which can only be acquired from a user authenticating (as far as I'm aware).

    Any further questions here though might be best to put to Netatmo directly. I am not part of Netatmo and don't have any direct link or contact with them (more than anyone does). I just made this for my own use and decided to put it out there publicly for other people to use. 😄 

2. As this is outside the application this is solely down to Netatmo and the system, and so sadly nothing you or I can add to achieve this. However I believe this is already possible (it shows for me in Safari on my physical device, but obviously doesn't work in the simulator).

3. If you mean here can you use your own account credentials to login with `NetatmoManager.login(username: ..., password: ...)` so people can use the app without their own account, no. As I said before, [Netatmo directly state](https://dev.netatmo.com/apidocumentation/oauth#client-credential) that that method of login should only be used for testing purposes.

    > This method should only be used for personnal use and testing purpose.

    The only reason I even implemented this into the SDK is for the Xcode tests, because I can't use the keychain, and so can't (currently) use the OAuth2 method for login to run tests. This is the reason it's marked as internal, to stop people using it. In the future I may remove this completely so that it's not even visible, but that would mean refactoring a lot of the OAuth2 token code which I don't have time to do at the moment. I went into more detail when in issue #3 when I detailed more on why:

    > The function to login with username and password is marked as internal for a couple of reasons, 1) it's marked in the Netatmo docs just to be used in testing and not in live production. So as the SDK gives a way of using the OAuth2 login function it's just used internally for the tests of the SDK. 2) Because I've added extra logic around the OAuth2 API as part of this SDK that automatically tracks, stores and refreshes tokens when it needs to (saving items in the keychain etc), I can only use the login for tests, as you don't get access to the keychain as a framework. (I lost a fair few hours working that ones out.)

4. I think my answer to your 3rd question should also answer this question.

**Comment by iKK001** [comment]
Thank you, James ! This makes perfect sense now to me.

I was not aware that a physical device (vs. simulator) does actually navigate to a "one-click-Accept"-Page and the user does not have to type the username and password there. Only on the simulator this username/pw entry is required. Which makes the entire Auth-process semi acceptable for a public weather usage. 

And moreover, I was not aware that the login-function only exists for Test-routines ! Makes perfect sense now as well !

Thank you very much for your detailed answers.
