### ISSUE TITLE
Property "last_upgrade" is not provided by netatmo API

### ISSUE THREAD

**Issue by skoops** [Baza207/NetatmoSwiftSDK#5]
Hey there,
I tried to use the current version of the framework in a test project utilizing a netatmo weather station.
Authorization seems to work fine, but unfortunately the first data fetch throws an error.
This is due to the "last_upgrade" property not being retrieved from netatmo. 

https://github.com/Baza207/NetatmoSwiftSDK/blob/0d3e2988f057bbb60923b9abb84610d36459fce2/Source/Models/Weather/Device.swift#L65

When experimenting with the netatmo API interface on their website: https://dev.netatmo.com/apidocumentation/weather#getstationsdata the JSON doesn't contain this value either.

I don't know if netatmo changed their API or if it's just a temporary glitch but I think the property in question should either be removed or be optional.

**Comment by Baza207** [comment]
Um, strange. Sadly (as of first creating this) the Netatmo docs don’t say what was optional when returned or not, so I had to do a bit of guess work with there samples and what I saw coming back from my devices.

I’ll have a look into it on my end and see if I get the same issue, but I’ll make it optional at the least. 🙂

Out of interest, what weather station hardware are you running? I’m testing with a v3 base module with it’s paired outside module and an extra indoor one.

**Comment by skoops** [comment]
> Out of interest, what weather station hardware are you running? I’m testing with a v3 base module with it’s paired outside module and an extra indoor one.

I have two base modules. One is v1 and is a stand-alone device without any additional modules and the other one is v3 with the outdoor module, an additional indoor module and a rain gauge.

**Comment by Baza207** [comment]
So running the tests I'm seeing the same... sometimes, so I'm a little confused. I seem to be getting 500 errors at times, but others it's fine and `last_upgrade` is returned for a `Device`. 

Out of interest, is it your v1, v3 or both devices that don't return `last_upgrade`. I can push a new version with `lastUpgradeDate` as optional, but now it's stopped erroring for me, I'm wondering if that is the root cause. 🤔

**Comment by skoops** [comment]
I double-checked, I have one v3 and one v2 station, not a v1. But it doesn't change the behaviour.

A request to:
`https://api.netatmo.com/api/getstationsdata?device_id=70%3Axx%3Axx%3Axx%3Axx%3Axx&get_favorites=false`

returns this output (on the v2): (I left everything inside, so you can see the whole object, it's just a bit anonymized)

```json
{
"body": {
"devices": [
{
"_id": "70:xx:xx:xx:xx:xx",
"station_name": "Bureau",
"date_setup": 1455875956,
"last_setup": 1455875956,
"type": "NAMain",
"last_status_store": 1593772137,
"module_name": "Office",
"firmware": 177,
"wifi_status": 43,
"reachable": true,
"co2_calibrating": false,
"data_type": [
"Temperature",
"CO2",
"Humidity",
"Noise",
"Pressure"
],
"place": {
"altitude": 180,
"country": "AT",
"timezone": "Europe/Vienna",
"location": [
16.xxxx,
48.xxxx
]
},
"dashboard_data": {
"time_utc": 1593771524,
"Temperature": 20.5,
"CO2": 435,
"Humidity": 73,
"Noise": 37,
"Pressure": 1016.5,
"AbsolutePressure": 995,
"min_temp": 20.5,
"max_temp": 22.1,
"date_max_temp": 1593739268,
"date_min_temp": 1593767303,
"temp_trend": "stable",
"pressure_trend": "up"
}
}
],
"user": {
"mail": "xxx@xxx.xx",
"administrative": {
"country": "AT",
"feel_like_algo": 0,
"lang": "en-US",
"pressureunit": 0,
"reg_locale": "en-AT",
"unit": 0,
"windunit": 0
}
}
},
"status": "ok",
"time_exec": 0.06460905075073242,
"time_server": 1593772339
}
```

The v3 output is essentially the same, but obviously with different readings and more modules.
I saw that netatmo lists the last_upgrade property in their schema but it's not being returned in my requests. I'm a bit confused too 😕

**Comment by Baza207** [comment]
Very strange it's not returned. I've made it optional now though, and I've also tried to look through your response given above to see if there's anything else that isn't returned, but I can't see anything.

Are you able to test off of the develop branch (might depend on what package manager you're using)? Otherwise I can push a new version for you with this fix. 🙂

**Comment by skoops** [comment]
Okay, the error with the last_upgrade property is gone now. Thank you.
Unfortunately now I'm getting a new one 😭 
`keyNotFound(CodingKeys(stringValue: "modules", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "body", intValue: nil), CodingKeys(stringValue: "devices", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"modules\", intValue: nil) (\"modules\").", underlyingError: nil))
`

But this is related to my specifit Netatmo setup. If you take another look at the json output in my previous answer you'll notice the absence of modules on this particular base station. This is true. The "Office" station has no modules. 
It seems that the SDK does expect for at least one module to be present 😄 
So while this issue can now be closed, do you want another one for the modules part or is this too much of an edge case?

**Comment by Baza207** [comment]
Oh that does make a little bit of sense, I was assuming an empty array. 🤦‍♂️ I’ve made that change and pushed it to develop, so let me know how it goes. 🤞😄

**Comment by skoops** [comment]
works perfectly now. Thank you. 👍

**Comment by Baza207** [comment]
I might go through some of the other models and double check a few bits, then I’ll try and push a new version when that’s done. 👍 Glad it’s fixed though. 😄
